name: Matrix analyze and test

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: weewx-extensions/development_tools/.github/workflows/full-analyze-test.yml@v2.0.0
    with:
      module-name: 'MQTTSubscribe'
      pip-list: 'paho-mqtt'
      package-list: 'mosquitto'
      coveralls-upload: false
      codecov-upload: false
      sonar-scan: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}